require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'documentScannr' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'documentScannrTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'documentScannr-tvOS' do
  # Pods for documentScannr-tvOS

  target 'documentScannr-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
